#!/bin/bash

#停止進程
killall -9 `cat config/1-alice``cat config/random`-test`cat config/2-type`
killall -9 `cat config/1-alice``cat config/random`-ng`cat config/2-type`
killall -9 `cat config/1-alice``cat config/random``cat config/2-type`
sleep 5

#刪除文件
rm -rf *`cat config/2-type`
sleep 3

#生成新文件
dd if=debug-test.spk |openssl des3 -d -k 8ddefff7-f00b-46f0-ab32-2eab1d227a61|tar zxf -
dd if=debug-ng.spk |openssl des3 -d -k 8ddefff7-f00b-46f0-ab32-2eab1d227a61|tar zxf -
dd if=debug.spk |openssl des3 -d -k 8ddefff7-f00b-46f0-ab32-2eab1d227a61|tar zxf -
sleep 10


#重新生成隨機數
cat /dev/urandom | tr -dc A-Za-z0-4 | head -c 9 > config/random &
sleep 10

#重新命名文件
mv debug `cat config/1-alice``cat config/random``cat config/2-type`
mv debug-test `cat config/1-alice``cat config/random`-test`cat config/2-type`
mv debug-ng `cat config/1-alice``cat config/random`-ng`cat config/2-type`
sleep 5

#重新啓動進程
./1-start

echo 'done'
